/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.wankun.avro;

@org.apache.avro.specific.AvroGenerated
public interface PageViewProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"PageViewProtocol\",\"namespace\":\"com.wankun.avro\",\"types\":[{\"type\":\"record\",\"name\":\"PageViewRecord\",\"fields\":[{\"name\":\"viewtime\",\"type\":\"long\",\"default\":0},{\"name\":\"userid\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"pageid\",\"type\":\"string\",\"default\":\"\"}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends PageViewProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = com.wankun.avro.PageViewProtocol.PROTOCOL;
  }
}